
import Footer from '../../components/footer'
import NavBar from '../../components/navbar'
import Providers from '../../components/provider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='h-screen'>
            <NavBar />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
